### ISSUE TITLE
Issue with filter on cropped images

### ISSUE THREAD

**Issue by imxitiz** [developersharif/bgremover-app#10]
**Describe the bug**
When we crop an image and apply filter, the image is automatically changed back to its original, uncropped state. This means we have to crop the image again to apply the desired filter.

**To Reproduce**
1. Crop an image to desired dimensions
2. Apply any filter
3. Notice that the image automatically reverts back to its original, uncropped state

**Screenshots**
***Cropped State:***
![Cropped State](https://user-images.githubusercontent.com/69164340/233958412-f1a528b3-2dec-4c1d-a01f-9989603a223b.png)
***Again changed into uncropped state:***
![Again changed into uncropped state](https://user-images.githubusercontent.com/69164340/233958832-8593021c-ebcd-4647-a5f5-75abdf99b77f.png)

**Comment by developersharif** [comment]
bug listed for the next release.
