### ISSUE TITLE
Provide Mac Support

### ISSUE THREAD

**Issue by atapas** [developersharif/bgremover-app#14]
**Is your feature request related to a problem? Please describe.**
No it is a feature request. The distributions and source code build is available for windows and Linux. Please provide for Mac too. It will help many creators using Mac.

**Describe the solution you'd like**
Installation Support on Mac with all the available features. I'm not aware of the solution though.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by developersharif** [comment]
Currently, we have no plan for Mac support. But Mac support will be available in the premium version.
