### ISSUE TITLE
Problem saving jpg

### ISSUE THREAD

**Issue by ZarinNegah** [developersharif/bgremover-app#16]
Hello
Good time
We need images with colored background and png format is not usable for us
And also only jpg format can be used for our work
Solutions are available on the Internet
Please upgrade

https://stackoverflow.com/questions/48206051/image-conversion-cannot-write-mode-rgba-as-jpeg

https://stackoverflow.com/questions/52497433/cannot-write-mode-rgba-as-jpeg-how-to-resolve-this-error-without-converting-imag

https://github.com/python-pillow/Pillow/issues/2609

**Comment by ZarinNegah** [comment]
Please check and help

**Comment by developersharif** [comment]
> Please check and help
**JPG** is now supported with Solid BG color or BG Image (Not in transparent BG)
check it out https://github.com/developersharif/bgremover-app/releases/download/v2.0.1/BG.Remover-beta-2.0.1.exe

**Comment by ZarinNegah** [comment]
hi
I still get the same error for jpg images

There is another problem with the pictures of women with hijab
![3dar4](https://github.com/developersharif/bgremover-app/assets/39865873/185bf3e1-5cf0-4bf4-8b00-0f0fe90eb92d)
![bgremover_tmphzrwp8vl](https://github.com/developersharif/bgremover-app/assets/39865873/c5fbb466-76ae-4522-8376-d665bdc0c5e9)

**Comment by developersharif** [comment]
we will add more capable ai model to increase the accuracy! (Next Major Version may be)

**Comment by ZarinNegah** [comment]
Do you have a possible time for the new version?
Because your program is really useful for me
And it is very good that jpg problems are solved completely

**Comment by developersharif** [comment]
> Do you have a possible time for the new version? Because your program is really useful for me And it is very good that jpg problems are solved completely
As a single developer I need time.  Being a free tool, development is not possible without free time!  But I will try to complete the next version quickly!

**Comment by ZarinNegah** [comment]
thanks dear
