### ISSUE TITLE
The size is reduced too much.

### ISSUE THREAD

**Issue by DevDavisNunez** [developersharif/bgremover-app#18]
**Describe the bug**
I load a higher resolution image and it returns a very small image.

**To Reproduce**
1. Go to File
2. Click on Open File
3. Select the image
4. Click Remove Background
5. Click Save Image

**Expected behavior**
It should remove the background while maintaining the original resolution of the image.

**Screenshots**
![image](https://github.com/developersharif/bgremover-app/assets/29848863/38a7da13-8d90-4eb3-ba63-28eca8cc41a8)
![image](https://github.com/developersharif/bgremover-app/assets/29848863/7add176d-5e8c-4b92-81ec-6122a0179b1a)

**Desktop (please complete the following information):**
 - OS: Win8
 - Browser chrome
 - Version 2.0

**Additional context**

**Comment by developersharif** [comment]
bug listed
