### ISSUE TITLE
Malwarebytes doesn't allows it!

### ISSUE THREAD

**Issue by BhawaniGarg** [developersharif/bgremover-app#2]
Don't know why but malwarebytes is not allowing this app to run and marking it as "virus".

**Comment by developersharif** [comment]
Thank you for bringing this issue to my attention. My app is free and open-source and does not have a code-signing certificate. I will investigate the issue and try to find a solution. You may temporarily disable Malwarebytes and try running the app again.

**Comment by BhawaniGarg** [comment]
where is the source code of the app? as you said its open source

**Comment by developersharif** [comment]
> where is the source code of the app? as you said its open source

It’s free of cost for users,not open source!

**Comment by BhawaniGarg** [comment]
earlier you said "My app is free and open-source" are you trying to inject virus into virus pc?

**Comment by developersharif** [comment]
> earlier you said "My app is free and open-source" are you trying to inject virus into virus pc?

Thank you for your question. To clarify, my application is free to use and distribute, but the code is not open-source. As for your concern about viruses, I can assure you that my software is completely safe and virus-free. You can download the application from my Github repository or from a trusted source. If you have any further questions or concerns, please don't hesitate to ask.
