### ISSUE TITLE
Its NOT OFFLLINE, requires internet to remove bg

### ISSUE THREAD

**Issue by iamodiner** [developersharif/bgremover-app#20]
**Describe the bug**
Its NOT OFFLLINE, requires internet to remove bg when its specifically mentioned that its offline remover. thats cheating

**To Reproduce**
1. Block the outgoing connection of this app with firewall

**Expected behavior**
image should have bg removed without internet

**Screenshots**
![image](https://github.com/developersharif/bgremover-app/assets/159020910/2be1afbc-bbb2-4eda-b268-d8e8528e34d0)

**Smartphone (please complete the following information):**
 - Device: PC
 - OS: Win 10 Latest

**Additional context**
This is plain misleading and cheating, you should mention in bold clear text that internet is required else would not have downloaded this crap at all.

**Comment by developersharif** [comment]
**Run the .bat file to download the model file. Then restart the program.**
https://github.com/developersharif/bgremover-app/blob/main/windows-model-download.bat

**Comment by iamodiner** [comment]
Why is model file not included in the first place if you are touting it as OFFLINE model?

and from opsec point, no one should ever be asked to run a .bat file ever. we have no idea what kind of damage it can do to your pc (Not in your case) just ask any sysadmin

You should either design your software that it doesn't phone home ever- to download any model files or send telemetry or you should be clear and be upfront that its not offline and requires either one time internet connection or whatever

offline means offline - period
