### ISSUE TITLE
When the background of the image is removed, the foreground element is lost

### ISSUE THREAD

**Issue by skyyan2000** [developersharif/bgremover-app#22]
When the background of the image is removed, the foreground element is lost

the source image
![a1](https://github.com/user-attachments/assets/4c5c9d5e-bf3a-4d1b-b119-776b46a0114a)

after processing image

![bgremover](https://github.com/user-attachments/assets/0d2b666a-b48d-49b8-8f58-726d99b30029)

**Comment by skyyan2000** [comment]
Want the picture
![a1-99](https://github.com/user-attachments/assets/6c366891-f8b0-43c8-9483-79c951bd3813)

**Comment by developersharif** [comment]
Its all about model!
