### ISSUE TITLE
How can i uninstall de app in linux (fedora)?

### ISSUE THREAD

**Issue by Zutterart** [developersharif/bgremover-app#23]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by developersharif** [comment]
Please provide the full info in English

**Comment by developersharif** [comment]
### https://github.com/developersharif/bgremover-app/blob/main/linux_uninstall.sh 

Run this bash script to uninstall bgremover offline.

**Comment by Zutterart** [comment]
Thank you! It works.
