### ISSUE TITLE
3/65 detections on virus total. 

### ISSUE THREAD

**Issue by necrovamp** [developersharif/bgremover-app#5]
https://www.virustotal.com/gui/file/930db8abacaecf81ac3d9f549ed90b37810f21943eacdc9edefb4c5e37d7a9ec

Artemis and Trojan.Generic, probably false positives, but what is concerning is the Trojan[PSW]/Python.Disco reported by Antiy-AVL

I dont know much about that company, but still make me a little uneasy? Is this all normal operation? 

Same detections tested on 2.0.0 ,  1.1.2 , and 1.1.0 (windows)

**Comment by necrovamp** [comment]
Version 2.0.0

**Comment by developersharif** [comment]
Thank you for bringing the issue to my attention. I understand your concern and would like to reassure you that I take the security of my software seriously.
They detected us as vurus, the major reason is we don't have code signing certificate. (Publisher not verified)
False positive detections are not uncommon, especially for software that is not digitally signed or does not have a publisher certificate. However, I will investigate the issue to ensure that the software is indeed safe to use.

In the meantime, please let me know if you have any further questions or concerns. Thank you for your patience and understanding.

**Comment by developersharif** [comment]
> https://www.virustotal.com/gui/file/930db8abacaecf81ac3d9f549ed90b37810f21943eacdc9edefb4c5e37d7a9ec
> 
> Artemis and Trojan.Generic, probably false positives, but what is concerning is the Trojan[PSW]/Python.Disco reported by Antiy-AVL
> 
> I dont know much about that company, but still make me a little uneasy? Is this all normal operation?
> 
> Same detections tested on 2.0.0 , 1.1.2 , and 1.1.0 (windows)

https://www.virustotal.com/gui/url/4e030c48f314e5d9f662f67cac85110bad541744105ee6bf82171a759e014763/details

**Comment by necrovamp** [comment]
Thanks for the update. I did get less detentions on the setup file. The virustotal results were based on the installed exe file, and not the setup file.
